### ISSUE TITLE
Trying to customise teslamate database and grafana datasource

### ISSUE THREAD

**Issue by instantdreams** [ajeckmans/TeslaMateOnK8s#1]
Thank you for an excellent guide, it is very useful indeed.

I am trying to create a kubernetes deployment for teslamate and grafana with a different database. I've followed your instructions to create the k8s structure and added the various helm repos.

These are the two commands I am using to install the two packages:
```
helm upgrade car1-teslamate billimek/teslamate --install --set virtualHost="https://car1-teslamate.$dnsZoneName" --set postgresqlDatabase=car1-postgresql
helm upgrade car1-grafana stable/grafana --install --values car1-values.yaml
```

The file car1-values.yaml has been attached, as a txt file:
[car1-values.yaml.txt](https://github.com/ajeckmans/TeslaMateOnK8s/files/5125480/car1-values.yaml.txt)

What I'd like to be able to confirm is what the correct names for the teslamate postgres source should be, versus what grafana uses internally. Once this is done this should support multi-vehicle deployment.

**Comment by ajeckmans** [comment]
Thanks :-)

I think in this case the data source url would be car1-teslamate-postgresql. In the teslamate helm chart it seems to follow the naming pattern '$release-name$-postgresql' the database would be car1-teslamate.

I'm not quite sure what your intended goal is though. Do you want a single grafana to show data for two separate teslamate instances or do you want two grafana instances as well?

**Comment by instantdreams** [comment]
My plan is to host complete sets for two of my buddies who have Teslas like this:
- Car 1
  - car1-teslamate : car1-teslamate.mydomain.com
  - car1-grafana : car1.mydomain.com
- Car 2
  - car2-teslamate : car2-teslamate.mydomain.com
  - car2-grafana : car2.mydomain.com

Both will be under the same Kubernetes cluster, just with different pod names & subdomains.

What I'll try in the grafana values is keeping everything the same apart from pointing to '$release-name$-postgresql' as the data source. I need to clear down my existing cluster and rebuild, as I've learned a lot as I've implemented your script.

**Comment by ajeckmans** [comment]
right :) In that case your setup would be fine. You'll end up with two complete separate stacks to which you can point those urls. 

There are more complicated setups you could look at which share the same postgres server, but with separate databases and two datasources in a single grafana instance and then fiddle with the permissions in grafana. That will save some of the resources on your k8s cluster and possibly make backups slightly easier.

**Comment by instantdreams** [comment]
This approach has been modified. Rather than adjusting the values, instead the plan is to deploy instances under kubernetes namespaces.
